development:
  adapter: mysql2
  encoding: utf8
  database: teamate
  pool: 5
  username: teamate
  password: teamate
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: t_teamate
  pool: 5
  username: teamate
  password: teamate
  socket: /tmp/mysql.sock

#production:
#  adapter: mysql2
#  encoding: utf8
#  database: p_Teamate
#  pool: 5
#  username: Teamate
#  password: Teamate
#  socket: /tmp/mysql.sock
