development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
#development:
#  adapter: mysql2
#  encoding: utf8
#  database: teamate
#  pool: 5
#  username: teamate
#  password: teamate
#
#test:
#  adapter: mysql2
#  encoding: utf8
#  database: t_teamate
#  pool: 5
#  username: teamate
#  password: teamate
#
#production:
#  adapter: mysql2
#  encoding: utf8
#  database: p_Teamate
#  pool: 5
#  username: Teamate
#  password: Teamate
#  socket: /tmp/mysql.sock
